### ISSUE TITLE
Can not run demo: Unhandled Runtime Error SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by sg552** [litentry/PolkaSignIn#8]
my environment: 

ubuntu 18
nodejs 16.14.0

# how to re-cur: 

1. yarn
2. cd demo/nextjs-demo
3. yarn dev

![image](https://user-images.githubusercontent.com/234533/156960851-e5704b9b-99d7-4605-b4de-07fe2e573924.png)

**Comment by sg552** [comment]
OK, I managed it solved.

open `packages/polkasignin-client/lib/inject-accounts.js`,  change this code: 

```
const signRaw = injector?.signer?.signRaw;
```

to 

```
    const result1 = injector
    const result2 = result1.signer
    const result3 = result2.signRaw
    const signRaw = result3
```

This is ugly but solved my problem.  Maybe author should specify a node version.

**Comment by bdmason** [comment]
Cheers @sg552, the `?.` syntax is a bit dangerous, I'll get rid.
